### ISSUE TITLE
compiling on ubuntu 18.04 results in an error when building houseedit.o

### ISSUE THREAD

**Issue by danielw97** [luciensadi/AwakeMUD#746]
**What can we help you with?**
Hi,
I'm attempting to build this project on ubuntu 18.04, however am receiving an error when houseedit.o is being compiled.
Could this be something to do with the version of boost I have installed, and if so is there a version that you recommend?
Thanks in advance for any help with this.
Here's the last lines of my compiler, although I'm happy to include more if it is helpful:

 ggdb  -c -o houseedit.o houseedit.cpp                                           
 houseedit.cpp:487:46: error: no member named 'copy_options' in namespace        
       'boost::filesystem'; did you mean 'copy_option'?                          
   bf::copy_file(old_file, new_save_file, bf::copy_options::overwrite_existing); 
                                          ~~~~^~~~~~~~~~~~                       
                                              copy_option                        
 /usr/include/boost/filesystem/operations.hpp:343:27: note: 'copy_option'        
       declared here                                                             
   BOOST_SCOPED_ENUM_START(copy_option)                                          
                           ^                                                     
 houseedit.cpp:487:60: error: no member named 'overwrite_existing' in            
       'boost::filesystem::copy_option'; did you mean 'overwrite_if_exists'?     
   bf::copy_file(old_file, new_save_file, bf::copy_options::overwrite_existing); 
                                          ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~   
                                                            overwrite_if_exists  
 /usr/include/boost/filesystem/operations.hpp:344:37: note:                      
       'overwrite_if_exists' declared here                                       
     {none=0, fail_if_exists = none, overwrite_if_exists};                       
                                     ^                                           
 2 errors generated.                                                             
 <builtin>: recipe for target 'houseedit.o' failed                               
 make: *** [houseedit.o] Error 1

**Comment by jdevnull** [comment]
You are correct, this is a result of what version of boost you have. At some point, the boost team changed `bf::copy_option::overwrite_if_exists` to `bf::copy_options::overwrite_existing`. If you follow the error message to the relevant location in the code (houseedit.cpp:487:46), you'll see:
```
#ifdef USE_OLD_BOOST
  bf::copy_file(old_file, new_save_file, bf::copy_option::overwrite_if_exists);
#else
  bf::copy_file(old_file, new_save_file, bf::copy_options::overwrite_existing);
#endif
```
Thus, all you need to do is add `#define USE_OLD_BOOST` somewhere earlier in the code to direct the preprocessor to the older form.

**Comment by danielw97** [comment]
Thanks for your speedy reply on this.
One other issue I'm running into however is here:
 boards.o: In function `__cxx_global_var_init.3':                                
 /usr/include/boost/system/error_code.hpp:210: undefined reference to `boost::system::system_category()'                                                         
Is it still preferred to build on 18.04, or is a different distro preferred?
Thanks.

**Comment by danielw97** [comment]
Thanks for the help, I've ended up just going with ubuntu 22.04 and that has worked fine.
One last question from me, is there a procedure for creating a first staff character?

**Comment by luciensadi** [comment]
No specific procedure. The first character who logs into a fresh database will be made level 10 (maximum) and treated as the owner of the game.

**Comment by danielw97** [comment]
Thanks for your help thus far on this.
I've had some issues and did a recompile, however am receiving this note when attempting to start the game:
Aug 18 09:22:10 :: ERROR: You need to run the pfiles_inv migration from the SQL 
 directory. Probable syntax from your AwakeMUD directory: `mysql -u YOUR_USERNAME
  -p AwakeMUD < SQL/Migrations/obj_idnums_and_vals.sql`.                         
 I'm not sure if the gensql script was supposed to do this, I'm running mariadb though which may be part of the problem.
Do I have to run all of the migrations to make sure things are setup correctly?
Thanks,

Daniel

**Comment by danielw97** [comment]
I'm not sure if it is the flags I'm building with, although on ubuntu 22.04 with the linux/others flags uncommented and a fresh pull from git I'm receiving the following:
 newhouse.cpp:(.text+0x889c): undefined reference to `boost::filesystem::path::fi
 lename() const'                                                                 
 /usr/bin/ld: newhouse.cpp:(.text+0x9322): undefined reference to `boost::filesys
 tem::path::filename() const'                                                    
 /usr/bin/ld: newhouse.o:newhouse.cpp:(.text+0x93df): more undefined references t
 o `boost::filesystem::path::filename() const' follow                            
 /usr/bin/ld: newhouse.o: in function `boost::filesystem::file_size(boost::filesy
 stem::path const&)':                                                            
 newhouse.cpp:(.text._ZN5boost10filesystem9file_sizeERKNS0_4pathE[_ZN5boost10file
 system9file_sizeERKNS0_4pathE]+0x15): undefined reference to `boost::filesystem:
 :detail::file_size(boost::filesystem::path const&, boost::system::error_code*)' 
 /usr/bin/ld: newhouse.o: in function `boost::filesystem::remove(boost::filesyste
 m::path const&)':                                                               
 newhouse.cpp:(.text._ZN5boost10filesystem6removeERKNS0_4pathE[_ZN5boost10filesys
 tem6removeERKNS0_4pathE]+0x15): undefined reference to `boost::filesystem::detai
 l::remove(boost::filesystem::path const&, boost::system::error_code*)'          
 /usr/bin/ld: /usr/bin/ld: DWARF error: invalid or unhandled FORM value: 0x23    
 vehicle_save_load.o: in function `load_saved_veh(bool)':                        
 vehicle_save_load.cpp:(.text+0x5ac1): undefined reference to `boost::filesystem:
 :path::filename() const'                                                        
 clang: error: linker command failed with exit code 1 (use -v to see invocation) 
 make: *** [Makefile:138: ../bin/awake.new] Error 1                              
 If there's a preferred distro to get this working on let me know, as I'm happy to spin up a vm to test any changes and would love to get this working.

**Comment by luciensadi** [comment]
> Thanks for your help thus far on this. I've had some issues and did a recompile, however am receiving this note when attempting to start the game: Aug 18 09:22:10 :: ERROR: You need to run the pfiles_inv migration from the SQL directory. Probable syntax from your AwakeMUD directory: `mysql -u YOUR_USERNAME -p AwakeMUD < SQL/Migrations/obj_idnums_and_vals.sql`. I'm not sure if the gensql script was supposed to do this, I'm running mariadb though which may be part of the problem. Do I have to run all of the migrations to make sure things are setup correctly? Thanks,
> 
> Daniel

Pull the newest copy, I merged the remaining migrations into gensql.sh. In the future, if it tells you to run a migration, just run that single one, and boot until it stops giving you new migrations to run.

> I'm not sure if it is the flags I'm building with, although on ubuntu 22.04 with the linux/others flags uncommented and a fresh pull from git I'm receiving the following:

Please submit error blocks with triple backticks like \`\`\`code\`\`\` so it's readable. That looks like you don't have boost filesystem installed though, try `apt install libboost-filesystem-dev`

**Comment by danielw97** [comment]
Hi again,
I think I've gotten my issues sorted, thanks again for the help.
One last question, everything seems to be working accept the initial money that characters start out with.
At the moment although there are shops etc durring character creation, the characters that I've created don't have any funds to use them, the same goes for attribute points.
Currently my characters don't have any to assign.
I'm not sure if this is by design, although wanted to note it down.

**Comment by jdevnull** [comment]
The pre-made archetypes have everything already assigned and spent. If you want to assign the points and spend the nuyen yourself, you'll want to choose to make a custom character. I don't think the chargen rooms provided by the world files include the archetype specific versions.

**Comment by luciensadi** [comment]
I'll go ahead and close this out. Hope all's going well with your port!
